steps:
  # Tests stage
  # - name: python:3.8.12-slim
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       pip install 'pytest==7.3.1'
  #       pip install 'pytest-custom-exit-code==0.3.0'
  #       pip install -U -r team_league/requirements.txt
  #       pytest -v --suppress-no-test-exit-code .

  # Build Flex Template Image stage
  - name: gcr.io/kaniko-project/executor:debug
    entrypoint: ''
    args:
      - /bin/sh
      - -c
      - |
        . ./export_env_variables.sh
        . ./build_image_kaniko.sh

  # Deploy Flex Template Spec File stage
  - name: google/cloud-sdk:420.0.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        . ./scripts/export_env_variables.sh
        . ./scripts/gcp_authentication.sh
        . ./scripts/create_flex_template_spec_file_gcs.sh

  # Run Dataflow Job stage
  - name: google/cloud-sdk:420.0.0
    entrypoint: /bin/sh
    args:
      - -c
      - |
        . ./scripts/export_env_variables.sh
        . ./scripts/gcp_authentication.sh
        . ./scripts/run_dataflow_job.sh

# Substitutions for environment variables
substitutions:
  _ENV_DEV: "dev"
  _GCLOUD_IMAGE_NAME: "google/cloud-sdk:420.0.0"
  _CI_SERVICE_NAME: "cloudbuild-ci"

# Specify when to trigger the steps
options:
  substitution_option: ALLOW_LOOSE

# Triggering options for each stage
timeout: 1200s

