steps:
  # Tests stage
  # - name: python:3.8.12-slim
  #   entrypoint: bash
  #   args:
  #     - -c
  #     - |
  #       pip install 'pytest==7.3.1'
  #       pip install 'pytest-custom-exit-code==0.3.0'
  #       pip install -U -r team_league/requirements.txt
  #       pytest -v --suppress-no-test-exit-code .
 
  # Step to check the branch name, set environment variables, and determine changed folders
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Determine the changed folders
        _CHANGED_FOLDERS=$(git diff --name-only HEAD~1 HEAD | grep '^dataflow-pipelines/Flex' | cut -d/ -f2 | sort -u)

        # Interrupt the build if no relevant changes are detected
        if [ -z "$_CHANGED_FOLDERS" ]; then
          echo "No relevant changes detected."
        else
          echo "Changes detected in the following folders: $_CHANGED_FOLDERS"
        fi

        # Save the environment variables and changed folders to a file for later steps
        echo "_CHANGED_FOLDERS=$_CHANGED_FOLDERS" >> /workspace/changed_folders


  # Build Flex Template Image stage
  - name: 'gcr.io/kaniko-project/executor:debug'
    entrypoint: '/busybox/sh'
    args:
      - -c
      - |
        pwd

  # Deploy Flex Template Spec File stage
  # - name: google/cloud-sdk:420.0.0
  #   entrypoint: /bin/sh
  #   args:
  #     - -c
  #     - |
  #       . ./scripts/export_env_variables.sh $_ENV
  #       . ./scripts/gcp_authentication.sh
  #       . ./scripts/create_flex_template_spec_file_gcs.sh

substitutions:
  _ENV: $_ENV
  _DATAFLOW_BUCKET: $_DATAFLOW_BUCKET
  _DOCKER_REPO_NAME: $_DOCKER_REPO_NAME

options:
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY

# Triggering options for each stage
timeout: 1200s